# Настройки подключения к базе данных PostgreSQL
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/oop_lab_db
spring.datasource.username=postgres
spring.datasource.password=titov16!
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки Hibernate для автоматического обновления таблиц
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Отключаем Flyway
spring.flyway.enabled=false

# Порт сервера
server.port=8082

# Отключаем автоматическую конфигурацию безопасности
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Логирование
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.com.equipment=DEBUG